@HostURL=https://localhost:7167
@UserName=hein.taljaard@gmail.com
@Password=P@ssw0rd123

#Register User
POST https://localhost:5000/api/users/register

{
  "email": {{UserName}},
  "password": {{Password}},
}