@HostURL=https://localhost:7167
@UserName=hein.taljaard@gmail.com
@Password=P@ssw0rd123

#Register User
POST {{HostURL}}/api/users/register
Content-Type: application/json

{
  "email": "{{UserName}}",
  "password": "{{Password}}"
}

###

#Login User
POST {{HostURL}}/api/users/login
Content-Type: application/json

{
  "email": "{{UserName}}",
  "password": "{{Password}}"
}