version: '3.7'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      MSSQL_SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - c:\code\docker\mytrade:/var/opt/mssql
    networks:
      - default

networks:
  default:
    driver: bridge